### ISSUE TITLE
When module update ?

### ISSUE THREAD

**Issue by ByJacob** [cloudposse/terraform-aws-iam-role#14]
I would like to ask when the module will be updated to the standards from terraform 0.12?
You can additionally consider that the versions of dependent modules are configured using variables.

**Comment by ByJacob** [comment]
@maximmi

**Comment by woz5999** [comment]
@maximmi @aknysh 

Is this module orphaned? it hasn't been updated to support tf .12 or .13. there's a PR introducing tf 12 support and adding tests open and unmerged since may.

**Comment by aknysh** [comment]
https://github.com/cloudposse/terraform-aws-iam-role/pull/15
