### ISSUE TITLE
Null provider is unused as direct dependency

### ISSUE THREAD

**Issue by Xerkus** [cloudposse/terraform-aws-iam-role#31]
## Describe the Bug
This module defines dependency on hashicorp/null but it is not used in this module. It is used indirectly via label module. I think it can be dropped as a dependency.

**Comment by nitrocode** [comment]
@Xerkus this would be a good PR :)

**Comment by Xerkus** [comment]
Wait, you want me to contribute? What is this, some kind Open Source?!
