### ISSUE TITLE
The terraform registry does not have the correct version of the module

### ISSUE THREAD

**Issue by eboboshka** [cloudposse/terraform-aws-iam-role#41]
## Describe the Bug
The terraform registry does not have the correct version of the module

## Expected Behavior
Terraform Registry lists the latest version 0.11.1, but Terraform gives an error when trying to use this version. On github the latest version is currently 0.15.0

```
╷
│ Error: Unresolvable module version constraint
│ 
│ There is no available version of module "registry.terraform.io/cloudposse/iam-role/aws" (role.tf:13) which matches the given version constraint.
│ The newest available version is 0.15.0.
╵

╷
│ Error: Unresolvable module version constraint
│ 
│ There is no available version of module "registry.terraform.io/cloudposse/iam-role/aws" (role.tf:13) which matches the given version constraint.
│ The newest available version is 0.15.0.
╵
```

## Steps to Reproduce
1. Open link https://registry.terraform.io/modules/cloudposse/eks-iam-role/aws/latest

## Screenshots
![image](https://user-images.githubusercontent.com/31067306/151857388-6c7c2a01-8433-4790-8282-0a7e471433b7.png)

![image](https://user-images.githubusercontent.com/31067306/151857337-577d43ac-cbe8-468f-92ba-5a894e066739.png)

**Comment by kevcube** [comment]
@eboboshka you made this issue under the wrong repository 😄 
This is `terraform-aws-iam-role`
but you're using `eks-iam-role`
