### ISSUE TITLE
Ability to construct aws_iam_policy_document data object inside the module from variable input

### ISSUE THREAD

**Issue by kevcube** [cloudposse/terraform-aws-iam-role#42]
## Describe the Feature

I am requesting the ability to pass a new input variable that defines a [aws_iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document) internal to the module, so that it gets constructed within the module rather than needing to pass in a JSON object to define the role policy.

This would enable all the modules inputs to be HCL rather than requiring a JSON input.

## Expected Behavior

A variable `iam_policy_object` or something that is a custom object which lines up with the structure of aws_iam_policy_document, and that variable is the input to a data source inside of the module that creates the iam policy document.

## Use Case

I prefer to define all infrastructure in HCL and use Terragrunt, so if I want to pass in a JSON object I usually use the terraform function `json_encode()` and pass in the HCL which would define the IAM policy. This would save me having to wrap my HCL inputs in `json_encode()`

## Describe Ideal Solution

see expected behavior

## Alternatives Considered

Using `json_encode()` isn't _terribly_ inconvenient

**Comment by kevcube** [comment]
@korenyoni in response to [slack](https://sweetops.slack.com/archives/CUJPCP1K6/p1645025772168289?thread_ts=1644540783.290799&cid=CUJPCP1K6)

**Comment by nitrocode** [comment]
@kevcube maybe we can implement the `iam_policy` module within this one

https://github.com/cloudposse/terraform-aws-iam-policy/

Then we can take a `iam_policy_statements` statements, check if it contains any statements, feed it to the module, and then pass it to

https://github.com/cloudposse/terraform-aws-iam-role/blob/d86dbaf7b5032c4bd4d56b73c115b122a777387a/main.tf#L40-L43

The `var.policy_documents` is already exposed, so you could do something like this

```hcl
module "iam_policy" {
  source  = "cloudposse/iam-policy/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "x.x.x"

  iam_policy_statements = {
    ListMyBucket = {
      effect     = "Allow"
      actions    = ["s3:ListBucket"]
      resources  = ["arn:aws:s3:::test"]
      conditions = []
    }

    # ...
  }
}

module "role" {
  source = "cloudposse/iam-role/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version     = "x.x.x"

  # ...

  policy_documents = [module.iam_policy.json]
}
```

**Comment by Nuru** [comment]
We want to avoid duplication of effort and maintenance by limiting modules to single tasks. This module's task is to create a role, not policies. 

You can separately use [terraform-aws-iam-policy](https://github.com/cloudposse/terraform-aws-iam-policy/), recently updated to take a full policy document as HCL (`iam_policy`), to create the policy or policies you want (output as JSON), and then feed them into this module via `policy_documents`, as @nitrocode [suggested above](https://github.com/cloudposse/terraform-aws-iam-role/issues/42#issuecomment-1106478242).

Closing as `wontfix`.
