### ISSUE TITLE
Cannot create role using only policy attachments

### ISSUE THREAD

**Issue by nate-selzer** [cloudposse/terraform-aws-iam-role#47]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

I'm attempting to create a role with no inline policies, just policy attachments. Here's how I'm instantiating the role module

```
module "role" {
  source  = "cloudposse/iam-role/aws"
  version = "0.16.2"

  context = module.this.context

  role_description = "blahblahblah"
}
```

The module then attempts to create a policy `module.role.aws_iam_policy.default[0]` with the following policy document
```
     + policy    = jsonencode(
            {
              + Statement = null
              + Version   = "2012-10-17"
            }
        )
 ```

## Expected Behavior
I expect the module to create no policies.

## Steps to Reproduce

Create a root component with the following configuration
```
module "role" {
  source  = "cloudposse/iam-role/aws"
  version = "0.16.2"

  context = module.this.context

  role_description = "blahblahblah"
}
```

Run `atmos terraform apply -s <stackname> role`

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

In a geodesic shell

## Additional Context
A potential workaround is to just create a valid, no-op policy document

**Comment by drselump14** [comment]
I had the same problem. Defining the `principals` property fixed it

**Comment by Nuru** [comment]
We may change this in a later release, but for now, for historical reasons, you must supply `policy_document_count`. Setting `policy_document_count = 0` will allow you to create a role with no inline policies. However, you still must defined principals who will be allowed to assume the role.
